$schema: "http://json-schema.org/draft-04/schema#"

id: "project"
title: Project
type: object
namespace: https://gdc.cancer.gov
category: administrative
project: '*'
program: '*'
description: >-
  Any specifically defined piece of work that is undertaken or attempted to meet a
  single requirement. (NCIt C47885)
additionalProperties: false
submittable: false
downloadable: false
previous_version_downloadable: false
validators: null

systemProperties:
  - id
  - state
  - released
  - releasable
  - intended_release_date

links:
  - name: programs
    backref: projects
    label: member_of
    target_type: program
    multiplicity: many_to_one
    required: true

required:
  - code
  - name
  - state
  - programs
  - dbgap_accession_number

uniqueKeys:
  - [id]
  - [code]

properties:

  awg_review:
    description: >-
      Indicates that the project is an AWG project.
    type: boolean
    default: false

  code:
    description: >-
      Project code
    type: string

  dbgap_accession_number:
    description: >-
      The dbgap accession number for the project.
    type: string

  disease_type:
    description: >-
      Full name for the project
    type: string

  id:
    $ref:
      - "_definitions.yaml#/uuid"
    description: >-
      UUID for the project

  in_review:
    description: >-
      Indicates that the project is under review by the submitter. Upload and data
      modification is disabled.
    type: boolean
    default: false

  intended_release_date:
    $ref:
      - "_definitions.yaml#/datetime"
    description: >-
      Tracks a Project's intended release date.

  is_legacy:
    description: >-
      Indicates whether a project will appear in the Legacy Archive.
    type: boolean
    default: false

  name:
    description: >-
      Display name for the project
    type: string

  primary_site:
    description: >-
      Primary site for the project
    type: string

  releasable:
    description: >-
      A project can only be released by the user when `releasable` is true.
    type: boolean
    default: false

  release_requested:
    description: >-
      User requests that the GDC release the project. Release can only be requested
      if the project is releasable.
    type: boolean
    default: false

  released:
    description: >-
      To release a project is to tell the GDC to include all submitted entities in
      the next GDC index.
    type: boolean
    default: false

  request_submission:
    description: >-
      Indicates that the user has requested submission to the GDC for harmonization.
    type: boolean
    default: false

  state:
    description: >-
      The possible states a project can be in.  All but `open` are equivalent to some
      type of locked state.
    default: open
    enum:
      - "closed"
      - "legacy"
      - "open"
      - "processed"
      - "processing"
      - "review"
      - "submitted"

  submission_enabled:
    description: >-
      Indicates if submission to a project is allowed.
    type: boolean
    default: true

  type:
    type: string

  programs:
    $ref: "_definitions.yaml#/to_one"
