---
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html

stages:
  - test
  - build
  - release_gdcdatamodel2

include:
  - project: nci-gdc/gitlab-templates
    ref: 0.2.1
    file:
      - templates/global/full.yaml
      - templates/python/full.yaml

variables:
  PRE_COMMIT_DOCKER_IMAGE: docker.osdc.io/ncigdc/python3.7-builder:${BASE_CONTAINER_VERSION}
  PIP_EXTRA_INDEX_URL: https://nexus.osdc.io/repository/pypi-all/simple
  TWINE_REPOSITORY_URL: "https://nexus.osdc.io/repository/pypi-snapshots/"

.override_gdcdictionary_version:
  rules:
    - if: $GDCDICTIONARY_TARGET_VERSION_OVERRIDE != null
      variables:
        GDCDICTIONARY_TARGET_VERSION: $GDCDICTIONARY_TARGET_VERSION_OVERRIDE
    - when: always
      variables:
        GDCDICTIONARY_TARGET_VERSION: $CI_COMMIT_REF_NAME


execute_plaster:
  image: docker.osdc.io/ncigdc/python3.8-builder:${BASE_CONTAINER_VERSION}
  stage: build
  script:
    - !reference [.load_github_key, script]
    - pwd
    - git clone git@github.com:NCI-GDC/gdcdatamodel2.git
    - cd gdcdatamodel2
    - git checkout "$GDCDICTIONARY_TARGET_VERSION" || git checkout -b "$GDCDICTIONARY_TARGET_VERSION"
    - git log -1
    - sed -i 's|version = .*|version ="'"$GDCDICTIONARY_TARGET_VERSION"'"|' plaster.toml
    - sed -i 's/is_git_tag = .*/is_git_tag = false/' plaster.toml
    - cat plaster.toml
    - bash plaster
    - git status
    - sed -i 's|gdcdictionary @ git+https://github.com/NCI-GDC/gdcdictionary.git@.*#egg=gdcdictionary|gdcdictionary @ git+https://github.com/NCI-GDC/gdcdictionary.git@'"$GDCDICTIONARY_TARGET_VERSION"'#egg=gdcdictionary|' setup.cfg
    - cat setup.cfg
  artifacts:
    paths:
      - gdcdatamodel2
    expire_in: 1 week
  rules:
    - !reference [.override_gdcdictionary_version, rules]
    - if: $CI_COMMIT_TAG
      when: never

push_datamodels_to_github:
  image: docker.osdc.io/ncigdc/python3.6-builder:${BASE_CONTAINER_VERSION}
  stage: release_gdcdatamodel2
  script:
    - !reference [.load_github_key, script]
    - cd gdcdatamodel2
    - cat setup.cfg
    - git status
    - git add .
    - git commit -m "Use gdcdictionary $GDCDICTIONARY_TARGET_VERSION $CI_COMMIT_SHA"
    - git push origin "$GDCDICTIONARY_TARGET_VERSION"
  allow_failure: true   # failure when no changes of models
  rules:
    - !reference [.override_gdcdictionary_version, rules]
    - if: $CI_COMMIT_TAG
      when: never
  needs: ['execute_plaster']


push_gdcdatamodels_tag_to_github:
  image: docker.osdc.io/ncigdc/python3.8-builder:${BASE_CONTAINER_VERSION}
  stage: .pre   # TODO: change to last
  variables:      # TODO: remove
    CI_COMMIT_TAG: 2.6.7
  script:
    - !reference [ .load_github_key, script ]
    - export
    - git clone git@github.com:NCI-GDC/gdcdatamodel2.git
    - cd gdcdatamodel2    # always tag develop
    - echo $CI_COMMIT_TAG
    - echo $CI_COMMIT_SHA
    - git tag -a $CI_COMMIT_TAG -m "gdcdictionary $CI_COMMIT_SHORT_SHA gdcdatamodel2 $(git rev-parse --short HEAD)"
    - git push origin $CI_COMMIT_TAG
  except:     # TODO: change to only
    - tags
