---
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html

stages:
  - test

include:
  - project: nci-gdc/gitlab-templates
    ref: 0.2.0
    file:
      - templates/global/full.yaml
      - templates/python/full.yaml

tox:
  stage: test
  image: ${BASE_CONTAINER_REGISTRY}/python${REPO_PY_VERSION}-builder:${BASE_CONTAINER_VERSION}
  parallel:
    matrix:
      - REPO_PY_VERSION: ["3.7", "3.8", "3.9"]
  script:
    - pip install tox
    - tox -e ${REPO_PY_VERSION}

tox legacy:
  stage: test
  image: ${BASE_CONTAINER_REGISTRY}/python36-builder:${LEGACY_BASE_CONTAINER_VERSION}
  script:
    - pip install tox
    - tox -e py36

.override_gdcdictionary_version:
  rules:
    - if: $GDCDICTIONARY_TARGET_VERSION_OVERRIDE != null
      variables:
        GDCDICTIONARY_TARGET_VERSION: $GDCDICTIONARY_TARGET_VERSION_OVERRIDE
    - when: always
      variables:
        GDCDICTIONARY_TARGET_VERSION: $CI_COMMIT_REF_NAME
