---
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml
include:
  - project: nci-gdc/gitlab-templates
    ref: master
    file:
      - templates/global/full.yaml
      - templates/python/full.yaml

variables:
 BASE_CONTAINER_VERSION: "1.4.0"
 PRE_COMMIT_DOCKER_IMAGE: docker.osdc.io/ncigdc/python3.8-builder:2.1.0
 DOCKER_BUILDKIT: 1
 PIP_EXTRA_INDEX_URL: https://nexus.osdc.io/repository/pypi-all/simple
 DOCKER_BUILD_OPTS: "--build-arg PIP_EXTRA_INDEX_URL=https://nexus.osdc.io/repository/pypi-all/simple"
 DOCKER_PUSH_OPTS: "--all-tags"

tox:
  image: ${BASE_CONTAINER_REGISTRY}/${REPO_PY_VERSION}-builder:${BASE_CONTAINER_VERSION}
  before_script:
    - mkdir -p /usr/share/man/man1

.python_versions:
  parallel:
    matrix:
      - REPO_PY_VERSION: ["python36"]

update_gdcdatamodel2:
  image: docker.osdc.io/ncigdc/python3.8-builder:2.1.0
  stage: build
  script:
    - !reference [.load_github_key, script]
    - pwd
    - git clone git@github.com:NCI-GDC/gdcdatamodel2.git
    - cd gdcdatamodel2
    - git checkout feat/dev-1686-move-plaster-dependency-out  # TODO remove this after merged
    - git checkout "$CI_COMMIT_REF_NAME" || git checkout -b "$CI_COMMIT_REF_NAME"
    - sed -i 's|version = .*|version ="'"$CI_COMMIT_REF_NAME"'"|' plaster.toml
    - sed -i 's/is_tag = .*/is_tag = false/' plaster.toml
    - cat plaster.toml
    - bash plaster
    - sed 's|gdcdictionary @ git+https://github.com/NCI-GDC/gdcdictionary.git@.*#egg=gdcdictionary|gdcdictionary @ git+https://github.com/NCI-GDC/gdcdictionary.git@'"$CI_COMMIT_REF_NAME"'#egg=gdcdictionary|' setup.cfg
    - cat setup.cfg
    - pip3 --version
    - pip3 install virtualenv pip-tools==6.3.0
    - pip-compile  --extra=dev --output-file=dev-requirements.txt pyproject.toml
    - git add .
    - git commit -m "$CI_COMMIT_SHA"
    - git push -u origin "$CI_COMMIT_SHA"
