---
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html

stages:
  - test

include:
  - project: nci-gdc/gitlab-templates
    ref: master
    file:
      - templates/global/full.yaml
      - templates/python/full.yaml

variables:
  BASE_CONTAINER_VERSION: "1.4.0"
  PRE_COMMIT_DOCKER_IMAGE: docker.osdc.io/ncigdc/python3.7-builder:2.2.0
  DOCKER_BUILDKIT: 1
  PIP_EXTRA_INDEX_URL: https://nexus.osdc.io/repository/pypi-all/simple
  DOCKER_BUILD_OPTS: "--build-arg PIP_EXTRA_INDEX_URL=https://nexus.osdc.io/repository/pypi-all/simple"
  DOCKER_PUSH_OPTS: "--all-tags"
  TWINE_REPOSITORY_URL: "https://nexus.osdc.io/repository/pypi-snapshots/"


tox:
  image: ${BASE_CONTAINER_REGISTRY}/${REPO_PY_VERSION}-builder:${BASE_CONTAINER_VERSION}
  before_script:
    - mkdir -p /usr/share/man/man1

.python_versions:
  parallel:
    matrix:
      - REPO_PY_VERSION: ["python36"]

docker_build:
  allow_failure: true
  rules:
    - when: never

release:
  image: docker.osdc.io/ncigdc/python36-builder:1.4.0
  allow_failure: true
  rules:
    - when: never

.override_gdcdictionary_version:
  rules:
    - if: $GDCDICTIONARY_TARGET_VERSION_OVERRIDE != null
      variables:
        GDCDICTIONARY_TARGET_VERSION: $GDCDICTIONARY_TARGET_VERSION_OVERRIDE
    - when: always
      variables:
        GDCDICTIONARY_TARGET_VERSION: $CI_COMMIT_REF_NAME
