version: "3.3"
services:
  app:
    image: quay.io/ncigdc/jenkins-agent:1.1.0
    environment:
      SSH_AUTH_SOCK: $SSH_AUTH_SOCK
      HTTPS_PROXY: http://cloud-proxy:3128
      HTTP_PROXY: http://cloud-proxy:3128
    volumes:
    - .:/home/jenkins
    - $SSH_AUTH_SOCK:$SSH_AUTH_SOCK
    command: bash -c "tox --recreate"
