[build-system]
requires = ["setuptools>=66", "wheel", "setuptools_scm[toml]>=7.0"]
build-backend = "setuptools.build_meta"

[project]
name = "gdcdictionary"
dynamic = [
  "version",
  "description",
  "readme",
  "requires-python",
  "license",
  "authors",
  "maintainers",
  "keywords",
  "classifiers",
  "urls",
  "scripts",
  "gui-scripts",
  "entry-points",
  "dependencies",
  "optional-dependencies"
]

[tool.black]
line-length = 98
include = '\.pyi?$'

[tool.coverage.html]
title = "gdcdictionary coverage report"
directory = "docs/htmlcov"
show_contexts = true

[tool.coverage.run]
branch = true
context = "unit tests"
source = ["gdcdictionary"]

[tool.isort]
profile = "black"
known_first_party = ["gdcdictionary"]

[tool.pytest.ini_options]
minversion = 6.0
# Silence warning by opting in to use pytest 6's new default value
junit_family = "xunit2"
junit_logging = "system-out"
console_output_style = "classic"
log_cli_level = "INFO"
log_cli = "true"
filterwarnings = ["ignore::DeprecationWarning"]
addopts = "-rfE --color=yes"
norecursedirs = [
  ".git",
  ".tox",
  "dist",
  "build",
  "examples",
  "sandbox"
]
testpaths = [
  "tests"
]

[tool.setuptools_scm]
local_scheme = "no-local-version"
