$schema: "http://json-schema.org/draft-04/schema#"

id: "project"
title: Project
type: object
program: '*'
project: '*'
category: administrative
description: >
  Any specifically defined piece of work that is undertaken or attempted to meet a single
  requirement. (NCIt C47885)
additionalProperties: false
submittable: false
downloadable: false
previous_version_downloadable: false
validators: null

systemProperties:
  - id
  - state
  - released
  - releasable
  - intended_release_date

required:
  - code
  - name
  - state
  - programs
  - dbgap_accession_number

uniqueKeys:
  - [id]
  - [code]

links:
  - name: programs
    backref: projects
    label: member_of
    target_type: program
    multiplicity: many_to_one
    required: true

constraints: null

# project properties
# code, disease_type and primary_site are in the current data model for project
# and likely shouldn't be
properties:
  type:
    type: string

  id:
    description: "UUID for the project" # TOREVIEW
    $ref: "_definitions.yaml#/UUID"
    systemAlias: node_id

  awg_review:
    description: >
      Indicates that the project is an AWG project.
    default: false
    type: boolean

  code:
    description: "Project code" # TOREVIEW
    type: string

  dbgap_accession_number:
    description: "The dbgap accession number for the project." # TOREVIEW
    type: string

  disease_type:
    description: "Full name for the project" # TOREVIEW
    type: string

  intended_release_date:
    description: Tracks a Project's intended release date.
    type: string
    format: date-time

  in_review:
    description: >
      Indicates that the project is under review by the submitter. Upload and data modification is disabled.
    default: false
    type: boolean

  is_legacy:
    description: >
      Indicates whether a project will appear in the Legacy Archive.
    default: false
    type: boolean

  name:
    description: "Display name for the project" # TOREVIEW
    type: string

  primary_site:
    description: "Primary site for the project" # TOREVIEW
    type: string

  state:
    description: >
      The possible states a project can be in.  All but `open` are
      equivalent to some type of locked state.
    default: open
    enum:
        # open: the only state users can perform 'upload' actions
        # possible actions in `open`:
        #   - upload (no state change)
        #   - review -> review
        #   - release (project.released -> true)
        - open

        # locked: admin has locked project for review
        # possible actions in `locked`:
        #   - open -> open
        #   - submit -> submitted
        #   - release (project.released -> true)
        - review

        # submitted: An admin has submitted project, it is locked against
        #            upload.
        # possible actions in `submitted`:
        #   - process -> processing
        #   - release (project.released -> true)
        - submitted

        # processing: The system is processing data in the project and
        #             is locked against upload and submission
        #   - (system transition to open)
        #   - release (project.released -> true)
        - processing

        - processed

        # closed: The closed state is introduced to replace the
        #         ``legacy`` state and means that no further action
        #         can be taken on the project
        #   - (system transition to open)
        #   - release (project.released -> true)
        - closed

        # DEPRECATED(2016-03-01): synonymous with closed. included for
        #                         backwards compatibility
        - legacy

  release_requested:
    description: >
      User requests that the GDC release the project. Release can only be requested if the project
      is releasable.
    default: false
    type: boolean

  released:
    description: >
      To release a project is to tell the GDC to include all submitted
      entities in the next GDC index.
    default: false
    type: boolean

  releasable:
    description: >
      A project can only be released by the user when `releasable` is true.
    default: false
    type: boolean

  request_submission:
    description: >
      Indicates that the user has requested submission to the GDC for harmonization.
    default: false
    type: boolean

  submission_enabled:
    description: >
      Indicates if submission to a project is allowed.
    default: true
    type: boolean

  programs:
    description: >
      Indicates that the project is logically part of the indicated project.
    $ref: "_definitions.yaml#/to_one"
