$schema: "http://json-schema.org/draft-04/schema#"

id: "workflow"
title: Workflow
type: object
category: analysis 
program: '*'
project: '*'
description: >
  Summary of analyses performed on file.
additionalProperties: false
validators: null

systemProperties:
  - id
  - project_id
  - state
  - created_datetime
  - updated_datetime

links:
  - exclusive: true # needs to point to either a submitted or generated file
    required: true
    subgroup:
      - name: submitted_files
        backref: workflows
        label: performed_on
        target_type: submitted_file
        multiplicity: one_to_many
        required: false
      - name: generated_file_inputs
        backref: workflows
        label: performed_on
        target_type: generated_file
        multiplicity: one_to_many
        required: false

required:
  - submitter_id
  - workflow_type
  - workflow_link
  - state

uniqueKeys:
  - [ id ]
  - [ project_id, submitter_id ]

properties:
  type:
    enum: [ "workflow" ]
  id:
    description: "TODO"
    $ref: "_definitions.yaml#/UUID"
    systemAlias: node_id
  submitter_id:
    description: "TOREVIEW: the file id assigned by the submitter"
    type: string
  workflow_type:
    description: "Analysis performed on file."
    enum:
      - BWA Alignment
      - Cocleaning
      - MuSE
      - SomaticSniper
      - VarScan
      - MuTect
      - LiftOver
      - HaplotypeCaller
      - BIC-seq
      - CNVnator
      - STAR 2-Pass
      - HTSeq
      - Cufflinks
      - Kallisto
      - DEXSeq
      - BCGSC miRNA Profiling
      - Other
  workflow_link:
    description: "Link to github location and hash for the cwl used."
    type: string
  state:
    $ref: "_definitions.yaml#/state"
  submitted_files:
    $ref: "_definitions.yaml#/to_one"
  generated_file_inputs:
    $ref: "_definitions.yaml#/to_one"
  project_id:
    type: string
  created_datetime:
    $ref: "_definitions.yaml#/datetime"
  updated_datetime:
    $ref: "_definitions.yaml#/datetime"
