$schema: "http://json-schema.org/draft-04/schema#"

id: "project"
title: Project
type: object
program: '*'
project: '*'
category: administrative
description: >
  Any specifically defined piece of work that is undertaken or attempted
  to meet a single requirement. (NCIt C47885)
additionalProperties: false
validators: null

system_properties:
  - id
  - project

required:
  - alias
  - name
  - state
  - member_of

unique_keys:
  - [id]
  - [alias]

links:
  - name: member_of
    link_to_type: project
    multiplicity: one_to_one

constraints: null

# project properties
# code, disease_type and primary_site are in the current data model for project
# and likely shouldn't be
properties:
  type:
    type: string
  id:
    $ref: "definitions.yaml#/UUID"
    systemAlias: node_id
    description: "TODO"
  alias:
    type:
      - string
      - "null"
    description: "TODO"
  name:
    type: string
    description: "TODO"
  state:
    type: string
    enum:
      - legacy
      - active
    description: >
      Whether the project is accepting new submissions (active)
      or closed (legacy).

  member_of:
    $ref: "definitions.yaml#/to_one"
