$schema: "http://json-schema.org/draft-04/schema#"

title: Project
type: object
namespace: http://gdc.nci.nih.gov
category: administrative
project: '*'
description: >
  Any specifically defined piece of work that is undertaken or attempted
  to meet a single requirement. (NCIt C47885)
additionalProperties: false
validators: []

system_properties:
  - project_id
  - project

required:
  - project_alias
  - project_type

oneof:
  required:
    - link_out_program_id
    - link_out_program_alias

unique_keys:
  - [project_id]
  - [project_id, project_alias]

# project properties
# code, disease_type and primary_site are in the current data model for project
# and likely shouldn't be
properties:
  type:
    type: string
  project_id:
    $ref: "definitions.yaml#/UUID"
    systemAlias: node_id
    description: "TODO"
  project_alias:
    type:
      - string
      - "null"
    description: "TODO"
  name:
    type: string
    description: "TODO"
  state:
    type: string
    enum:
      - legacy
      - active
    description: >
      Whether the project is accepting new submissions (active)
      or closed (legacy).


# project parents
# Right now following general setup that allows having more than one parent
# Perhaps should limit to only allow a project to belong to one program?
    link_out_program_id:
      $ref: "definitions.yaml#/UUID"
      link_to_type: program
      multiplicity: oneToOne
    link_out_program_alias:
      type: string
      link_to_type: program
      multiplicity: oneToOne
